name: iOS IPA Signer

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: 'IPA Direct URL'
        required: true
      p12_url:
        description: 'P12 Certificate URL'
        required: true
      prov_url:
        description: 'MobileProvision URL'
        required: true
      password:
        description: 'P12 Password'
        required: true

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip libssl-dev build-essential

      - name: Build zsign
        run: |
          git clone https://github.com/zhlynn/zsign.git
          cd zsign
          g++ *.cpp common/*.cpp -lcrypto -O3 -o zsign
          sudo cp zsign /usr/local/bin/

      - name: Download Files
        run: |
          wget -q "${{ github.event.inputs.ipa_url }}" -O app.ipa
          wget -q "${{ github.event.inputs.p12_url }}" -O cert.p12
          wget -q "${{ github.event.inputs.prov_url }}" -O cert.mobileprovision

      - name: Sign the IPA
        run: zsign -k cert.p12 -p '${{ github.event.inputs.password }}' -m cert.mobileprovision app.ipa -o signed_app.ipa

      - name: Upload Signed IPA
        uses: actions/upload-artifact@v4
        with:
          name: Signed-IPA
          path: signed_app.ipa
